name: Build packages
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y devscripts wget equivs

    - name: Download sources
      run: |
        wget -nc https://github.com/apple/swift-corelibs-libdispatch/archive/refs/tags/swift-5.5-RELEASE.tar.gz -O libdispatch_5.5.orig.tar.gz

    - name: Install build dependencies
      working-directory: libdispatch-5.5/
      run: |
        mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
        rm -f *.deb *.buildinfo *.changes

    - name: Build packages
      working-directory: libdispatch-5.5/
      run: |
        tar -xvzf ../libdispatch_5.5.orig.tar.gz --strip-components=1
        debuild

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: debian
        path: |
          *.deb
          *.dsc
