name: Build packages
on: push

jobs:
  runtime:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    strategy:
      matrix:
        include:
          - library: libdispatch-5.5
            download: https://github.com/apple/swift-corelibs-libdispatch/archive/refs/tags/swift-5.5-RELEASE.tar.gz
            orig: libdispatch_5.5
          - library: libobjc2-2.1.20220927
            download: https://github.com/gnustep/libobjc2/archive/35ac9bc072e652e8bac9cd501f94d3b089b8f9a2.tar.gz
            orig: libobjc2_2.1.20220927

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y devscripts wget equivs

    - name: Download sources
      run: |
        wget -nc ${{ matrix.download }} -O ${{ matrix.orig }}.orig.tar.gz

    - name: Install build dependencies
      working-directory: ${{ matrix.library }}/
      run: |
        mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
        rm -f *.deb *.buildinfo *.changes

    - name: Build packages
      working-directory: ${{ matrix.library }}/
      run: |
        tar -xvzf ../${{ matrix.orig }}.orig.tar.gz --strip-components=1
        debuild

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: debian
        path: |
          *.deb

    - name: Upload package sources
      uses: actions/upload-artifact@v3
      with:
        name: sources
        path: |
          *.orig.tar.gz
          *.diff.gz
          *.debian.tar.xz
          *.dsc

  gnustep-make:
    needs: runtime

    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    strategy:
      matrix:
        include:
          - library: gnustep-make-2.9.0
            download: https://github.com/gnustep/tools-make/releases/download/make-2_9_0/gnustep-make-2.9.0.tar.gz
            orig: gnustep-make_2.9.0

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: debian
        
    - name: Install dependencies
      run: |
        dpkg -i libdispatch0_5.5-1_amd64.deb
        dpkg -i libdispatch-dev_5.5-1_amd64.deb
        dpkg -i libobjc2_2.1.20220927-1_amd64.deb
        dpkg -i libobjc2-dev_2.1.20220927-1_amd64.deb

        apt-get update
        apt-get install -y devscripts wget equivs

    - name: Download sources
      run: |
        wget -nc ${{ matrix.download }} -O ${{ matrix.orig }}.orig.tar.gz

    - name: Install build dependencies
      working-directory: ${{ matrix.library }}/
      run: |
        mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
        rm -f *.deb *.buildinfo *.changes

    - name: Build packages
      working-directory: ${{ matrix.library }}/
      run: |
        tar -xvzf ../${{ matrix.orig }}.orig.tar.gz --strip-components=1
        debuild

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: debian
        path: |
          *.deb

    - name: Upload package sources
      uses: actions/upload-artifact@v3
      with:
        name: sources
        path: |
          *.orig.tar.gz
          *.diff.gz
          *.debian.tar.xz
          *.dsc

  gnustep-base:
    needs: gnustep-make

    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    strategy:
      matrix:
        include:
          - library: gnustep-base-1.28.20221211
            download: https://github.com/gnustep/libs-base/archive/47b6e9d052498c386cd20aa33059bc998181eacd.tar.gz
            orig: gnustep-base_1.28.20221211

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: debian
        
    - name: Install dependencies
      run: |
        dpkg -i libdispatch0_5.5-1_amd64.deb
        dpkg -i libdispatch-dev_5.5-1_amd64.deb
        dpkg -i libobjc2_2.1.20220927-1_amd64.deb
        dpkg -i libobjc2-dev_2.1.20220927-1_amd64.deb
        dpkg -i gnustep-make_2.9.0-2_amd64.deb

        apt-get update
        apt-get install -y devscripts wget equivs

    - name: Download sources
      run: |
        wget -nc ${{ matrix.download }} -O ${{ matrix.orig }}.orig.tar.gz

    - name: Install build dependencies
      working-directory: ${{ matrix.library }}/
      run: |
        mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
        rm -f *.deb *.buildinfo *.changes

    - name: pkg-config diagnostics
      run: |
        pkg-config --variable pc_path pkg-config
        ls -l /usr/lib/x86_64-linux-gnu/pkgconfig/

    - name: Build packages
      working-directory: ${{ matrix.library }}/
      run: |
        tar -xvzf ../${{ matrix.orig }}.orig.tar.gz --strip-components=1
        DEB_BUILD_OPTIONS=nocheck debuild

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: debian
        path: |
          *.deb

    - name: Upload package sources
      uses: actions/upload-artifact@v3
      with:
        name: sources
        path: |
          *.orig.tar.gz
          *.diff.gz
          *.debian.tar.xz
          *.dsc

  gnustep-gui:
    needs: gnustep-base

    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    strategy:
      matrix:
        include:
          - library: gnustep-gui-0.29.20221128
            download: https://github.com/gnustep/libs-gui/archive/67d27cd4535e5e14b697f8def909807c8255a023.tar.gz
            orig: gnustep-gui_0.29.20221128

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: debian
        
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y devscripts wget equivs

        apt-get install -y libavahi-client3 libicu70 libxml2 libxslt1.1
        dpkg -i libdispatch0_5.5-1_amd64.deb
        dpkg -i libdispatch-dev_5.5-1_amd64.deb
        dpkg -i libobjc2_2.1.20220927-1_amd64.deb
        dpkg -i libobjc2-dev_2.1.20220927-1_amd64.deb
        dpkg -i gnustep-make_2.9.0-2_amd64.deb
        dpkg -i libgnustep-base1.28_1.28.20221211-1_amd64.deb
        dpkg -i libgnustep-base-dev_1.28.20221211-1_amd64.deb

    - name: Download sources
      run: |
        wget -nc ${{ matrix.download }} -O ${{ matrix.orig }}.orig.tar.gz

    - name: Install build dependencies
      working-directory: ${{ matrix.library }}/
      run: |
        mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
        rm -f *.deb *.buildinfo *.changes

    - name: pkg-config diagnostics
      run: |
        pkg-config --variable pc_path pkg-config
        ls -l /usr/lib/x86_64-linux-gnu/pkgconfig/

    - name: Build packages
      working-directory: ${{ matrix.library }}/
      run: |
        tar -xvzf ../${{ matrix.orig }}.orig.tar.gz --strip-components=1
        debuild

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: debian
        path: |
          *.deb

    - name: Upload package sources
      uses: actions/upload-artifact@v3
      with:
        name: sources
        path: |
          *.orig.tar.gz
          *.diff.gz
          *.debian.tar.xz
          *.dsc
